package com.medcorp.nevo.validic.model;

import java.io.Serializable;

/**
 * Created by gaillysu on 16/3/8.
 */
public class NevoUser {
    private String uid;  //auto generated by Nevo API
    private String token;
    private String msg;
    private int error;
    private String referer;
    private String state;
    private String validicID;//auto generated by validic API
    private String loginEmail;
    private String lastValidicRecordID;//when user create/update the last validic record, save its to here

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public int getError() {
        return error;
    }

    public void setError(int error) {
        this.error = error;
    }

    public String getReferer() {
        return referer;
    }

    public void setReferer(String referer) {
        this.referer = referer;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getValidicID() {
        return validicID;
    }

    public void setValidicID(String validicID) {
        this.validicID = validicID;
    }

    public String getLoginEmail() {
        return loginEmail;
    }

    public void setLoginEmail(String loginEmail) {
        this.loginEmail = loginEmail;
    }

    public String getLastValidicRecordID() {
        return lastValidicRecordID;
    }

    public void setLastValidicRecordID(String lastValidicRecordID) {
        this.lastValidicRecordID = lastValidicRecordID;
    }
}
