package com.medcorp.database.entry;


import net.medcorp.library.ble.util.Optional;

import java.util.Date;
import java.util.List;


public interface iSettingDatabaseHelper<T> {

    public Optional<T> add(T object);
    public boolean update(T object);

    /**
     * rid is the record ID generated by sqlLite database
     * @param rid
     * @return
     */
    public boolean remove(int rid);
    public List<Optional<T>> get(int rid);
    public List<Optional<T>> getAll();

    public List<T> convertToNormalList(List<Optional<T>> optionalList);

}
